### ISSUE TITLE
Error status codes that have been handled in special headers shouldn't log errors to console

### ISSUE THREAD

**Issue by cortesi** [intercoolerjs/intercooler-js#159]
Thanks for responding so quickly regarding header processing on error status codes. A little bit more is needed to make this usable. When I redirect the user to a login page, an error is still printed to console. I feel intercooler should either a) silence console logs when a special header is set on an error status code response, or b) provide some way to globally silence console logs for production. Perhaps both.

**Comment by carsongross** [comment]
This is an old one, but I agree: these errors should only show up in the console in a development setup.

I will fix this in the next release.
