### ISSUE TITLE
Add ic-refresh

### ISSUE THREAD

**Issue by nzjrs** [intercoolerjs/intercooler-js#205]
I'm currently serving a server generated image from my webapp.

To refresh this image at regular intervals I am setting `ic-poll` on the parent div, and then returning the complete `<img src='/XXX.jpg'>` text. This then subsequently causes a request to `/XXX.jpg` where I can return the newly updated generated image.

This seems a little roundabout. I was wondering if adding something like `ic-attr-refresh` or `ic-src-refresh` to intercooler.js made sense. `ic-src-refresh` for example, would replace or append the `src` attribute the normal `"?timestamp=" + new Date().getTime()` trick to entice a refresh.

Hope this makes sense and conceptually is compatible with intercooler's view of the world.

**Comment by carsongross** [comment]
This makes good sense, but I can't come up with a good syntax for it that doesn't get close to what the jQuery would look like.  You need to cache bust to make the request work and that makes the syntax difficult.

I like the idea, just don't see how to implement it cleanly yet.

**Comment by n3storm** [comment]
django like queries? ic-poll__src, ic-poll__data-values
this will replace attribute src with ic-get results and will replace attribute data-values from ic-get results
