### ISSUE TITLE
Infinite Scroll issue on chrome/android

### ISSUE THREAD

**Issue by muralikg** [intercoolerjs/intercooler-js#215]
Infinite scrolling doesn't work beyond the first load specifically on Chrome/Android. It seems to working fine on all desktop browsers and also on Firefox mobile.

Remote inspecting the mobile chrome tab did not show any errors either.

Browser: Chrome 59 / Android 6.0.1 
Trying to load the [Infinite Scroll](http://intercoolerjs.org/examples/infinitescroll.html) example.

Has anyone else observed this ?

**Comment by niallobrien** [comment]
Works fine for me here.

**Comment by baumann74** [comment]
Yes. I experience the same problem. Works fine the first time. Nothing happens after that. Really a shame because it is such a cool feature.

Chrome: 66
Android: 6.01.

**Comment by muralikg** [comment]
Tried it again on Android 7.1.2 / Chrome 66.0.3359 and still notice the issue

**Comment by baumann74** [comment]
So Google fixed it between Android 7.1.2 and 8.0.0?

**Comment by baumann74** [comment]
I tend to think that it is indeed a intercooler problem because this demo is working fine on my Android + Chrome: https://infinite-scroll.com/demo/full-page/.

@carsongross : Any ideas?

**Comment by carsongross** [comment]
This is a tough one: we are relying on the device properly telling us that the element has scrolled into view:

```javascript
  function isScrolledIntoView(elem) {
    elem = $(elem);
    if (elem.height() == 0 && elem.width() == 0) {
       return false;
    }
    var docViewTop = $(window).scrollTop();
    var docViewBottom = docViewTop + $(window).height();

    var elemTop = elem.offset().top;
    var elemBottom = elemTop + elem.height();

    return ((elemBottom >= docViewTop) && (elemTop <= docViewBottom)
    && (elemBottom <= docViewBottom) && (elemTop >= docViewTop));
  }```

I can see this being a bit wonky on some mobile browsers, but as far as I can tell the logic is sound.

Any opinions?

**Comment by psema4** [comment]
Works on Android 5.0.1 + Chrome 66.0.3359.  IIRC, the [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) is specifically indicated for this use case.
