### ISSUE TITLE
Intercooler events not firing when building with Webpack

### ISSUE THREAD

**Issue by lmartins** [intercoolerjs/intercooler-js#221]
Hi,

I have been using this plugin for a while without issues, however since I've tried to upgrade to the latest version it never worked again.

I'm using Webpack to build the project, and since the package does not play well with a Webpack build, I had to set an alias so it points to the file library location `intercooler: "intercooler/src/intercooler.js"` 

Problem is, event though the project builds and I get Intercooler in the global Scope (https://cl.ly/3s010V1L3B1y), the events are not firing. Things like `beforeSend.ic` or `pushUrl.ic` work, event though nothing change on the codebase where I'm creating those listeners.

Weirdly enough, the URL does update (i have push configured) the actual contents it should replace does not change either.

Any idea on where this might be going wrong?

**Comment by carsongross** [comment]
It sounds like Intercooler isn't initalizing properly when it loads.

Do you see anything in the console?  Is the "Intercooler" global symbol available?

Cheers,
Carson

**Comment by lmartins** [comment]
Hi @carsongross,

Thanks so much for the feedback.
I see one of two things happening. 

Using the version `1.0.3`, and loading it via Webpack with the Expose Loader `require("expose-loader?Intercooler!intercooler");` when I inspect the `Intercooler` object on the console I get an empty object. Interestingly enough, it shows the same output on the currently live site but there it works just fine.

If I use the latest version, loading it into the app using the same method, I still get an empty object.

On both situations above, when I click links the URL changes (using the push to history feature) but the content stays unchanged and the events I'm listening don't fire.

Btw, these are the event listeners I have declared:

```js
       jQuery(".js-loopNavigation a").on("beforeSend.ic", function(
            evt,
            elt,
            data
        ) {
            console.log("BEFORE SEND IC");
            self.onBeforeLoadPosts(evt, elt, data);
        });

        jQuery("body").on("complete.ic", function(
            evt,
            elt,
            data,
            status,
            xhr,
            requestId
        ) {
            console.log("COMPLETE IC");
            self.onPostsLoaded(evt, elt, data, status, xhr, requestId);
        });

        jQuery("body").on("pushUrl.ic", function(evt, target, data) {
            console.log("IC PUSH URL");
            self.triggerGAEvents();
        });
```

This is a WordPress site, where I'm loading the default jQuery version (2.2.0), so I've also tried loading the script directly from the CDN and strangely I get the same result.

Any idea why the push URL would work but not the events?

**Comment by lmartins** [comment]
@carsongross maybe I can get around it in a different way.
I'm loading the script from the CDN, instead of including it on the Webpack build. For some reason the events don't fire still, but I do get the contents from the response.

The issue with this approach, and this might be a different issue altogether, is that the library breaks other libraries functionality. This site uses a library called FacetWP, which is also ajax based.

Once I load Intercooler from the CDN, any ajax call from FacetWP is halted by an error on Intercooler script:
![image](https://user-images.githubusercontent.com/151981/31306906-973b9278-ab51-11e7-8e96-d12f351c08c2.png)

Which refers to this part of the script:
![image](https://user-images.githubusercontent.com/151981/31306909-a867c95e-ab51-11e7-9745-315298e53d2d.png)

Finally, inspecting the `Intercooler` object on the console does retrieve a non-empty object this time: 
![image](https://user-images.githubusercontent.com/151981/31306923-059eb362-ab52-11e7-97b5-88e5ff9677b7.png)

Thanks so much for any help you may provide.

**Comment by carsongross** [comment]
I'm fine with that fix, can you create a pull request against development?
