### ISSUE TITLE
target input type text should set the value attribute

### ISSUE THREAD

**Issue by redochka** [intercoolerjs/intercooler-js#229]
Hello,

when targeting an input type text, intercooler is injecting the response into the input tag as text child element instead of setting the value attribute:

- now (bad behaviour)
`<input type="text>SERVER Response (does not make sense)</input>`

- wanted 
`<input type="text value="SERVER Response" />`

**Comment by carsongross** [comment]
That's a good idea, I will look at it for the next release.  In the meantime you can use 'ic-replace-target' and replace the entire input w/ the desired HTML.

**Comment by jvosloo** [comment]
+1 for this!

**Comment by yeonsh** [comment]
+1

**Comment by oliverdarvall** [comment]
+1

**Comment by chg20** [comment]
Alright folks, in intercooler 2.0 (renamed kutty) you would just replace the whole input with a `outerHTML` response

**Comment by redochka** [comment]
@chg20 that's cool. Isn't new intercooler named htmx?

**Comment by chg20** [comment]
yep, kutty was the original name, but it meant too many different things in other langauges.

so it's htmx now:

htps://htmx.org

**Comment by redochka** [comment]
Great, **htmx** is a cool name. Long live to **htmx**
