### ISSUE TITLE
ic-indicator: Function hideIndicator is called twice when ic-push-url is true

### ISSUE THREAD

**Issue by baumann74** [intercoolerjs/intercooler-js#244]
I have found that the function `hideIndicator` is called twice when `ic-push-url="true"`. `hideIndicator` is then called on both `on-success` and `on-complete`. This causes a problem when the `ic-use-transition` attribute is used. The first time `hideIndicator` is called it will correctly re-add the `ic-use-transition`. But the second time (on-complete) it will call `elt.hide();`. This means that the indicator will not be shown the next time the button is clicked, i.e. the request is in progress.

Any suggestions or workarounds?

**Comment by carsongross** [comment]
Hi Anders,

Can you reproduce in a test?

Cheers,
Carson

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by baumann74** [comment]
```
<style>
  .ic-use-transition {
	visibility: hidden;
  }
</style>
<div>
	<a href=""
		ic-get-from="/Page1"
		ic-target="#content"
		ic-push-url="true"
		ic-indicator="#indicator">
		Page1
	</a>
	<a href=""
		ic-get-from="/Page2"
		ic-target="#content"
		ic-push-url="true"
		ic-indicator="#indicator">
		Page2
	</a>
	<i id="indicator" class="fa fa-spinner fa-spin ic-use-transition"></i>
	<div id="content" ic-history-elt="">
		<h1>Content</h1>
	</div>
</div>
```
Page1 and Page2 can just return a simple text on the server side.

The progress indicator is shown the first time you click one of the links. But nothing the second time. Because it now has the style `display:none` since `elt.hide` was called. 
As far as I can see this problem is solved if you remove the line `requestCleanup(indicator, elt); // clean up before snap-shotting HTML` from the `success` handling. The progress indicator is still removed because the `complete` handler also calls `requestCleanup`.

Just to clarify: I would like to use the CSS transition `visibility:hidden` on the indicator instead of the default `display:none` (show/hide) because with `visibility:hidden` the element takes up space while hidden. With `display:none` it doesn't. This means that with `display:none` the indicator can shift other elements when it appears.

**Comment by baumann74** [comment]
Does the example make sense? Should I make a pull request with a fix?

**Comment by carsongross** [comment]
That would be great!

Cheers,
Carson

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by baumann74** [comment]
Hi Carson.
Sorry for taking so long. Here is the pull request: https://github.com/LeadDyno/intercooler-js/pull/247. It includes test. Mind that the test cannot be run locally because they involve "History" functionality.

**Comment by baumann74** [comment]
Pull request is accepted.
