### ISSUE TITLE
Runs out of control when ic-src return an 302 (url redirection)

### ISSUE THREAD

**Issue by jespervestergaard** [intercoolerjs/intercooler-js#245]
Example from Reference:
` <div ic-src="/page_that_returns_302" ic-poll="5s">You have been on this page for 0 seconds...</div>`

If ic-src returns an 302 code intercooler slowly starts running out of control.

It is even worse if also using ic-trigger-on="load":
` <div ic-trigger-on="load" ic-src="/page_that_returns_302" ic-poll="5s">You have been on this page for 0 seconds...</div>`

**Comment by carsongross** [comment]
Does the page just keep returning a 302?  Eventually it returns data, right?
