### ISSUE TITLE
Pjax-like functionality

### ISSUE THREAD

**Issue by niallobrien** [intercoolerjs/intercooler-js#248]
Hi, would it be possible to have Pjax like functionality for all links without requiring additional attributes to be placed on link tags? Perhaps this could be activated globally via the API and whenever you wanted to disable this functionality per link, only then would you add an attribute.
So this functionality, other than just fetching the intended link via XHR and swapping the `<body>` content, it would also maintain browser history.
What are your thoughts? Thanks.

**Comment by mattburton** [comment]
I'll toss my hat in the ring here as well - I've wanted this in the past too - automatic pjax/turbolinks-style link interception. For the use cases I've wanted it an opt-in at the parent level would suffice - i.e. a list of links in a menu div, list of items, etc... I've gotten by with writing links like this in those scenarios:

`<a href="javascript:;" ic-get-from="...">`

Which is obviously less than ideal and breaks the whole notion of progressive enhancement - if JavaScript is disabled those links aren't going to do anything of course, so I try to use them sparingly.

On the other hand if those links could be standard links, and I just had to add an `ic-intercept-links="true"` attribute or similar to a parent element (i.e. it could be on the body if I so chose) that would be great, and I could handle returning partials or full views server side based on whether it was Intercooler initiating the request. In that vein being able to supply an `ic-target` along with that attribute would be a bonus, but it could be that it already works that way today, in which case _magic_.

**Comment by keyurshah** [comment]
I have to implement this type of functionality but my page has many links and it would be an annoyance to maintain.  I was going to use turbolinks but I’d rather not as I know there maybe some conflicts. 

Did anyone figure out a solution for this?

**Comment by mattburton** [comment]
@keyurshah while I haven't had a chance to try it myself, it looks like what you were after was added in the last release:

http://intercoolerjs.org/attributes/ic-enhance.html

**Comment by chg20** [comment]
ic-enhance kinda did this, mixed in with turbolinks functionality

the functionality has been moved into kutty as the kt-boost attribute:

https://kutty.org/attributes/kt-boost/
