### ISSUE TITLE
Smaller jQuery / ZeptoJS alternative Cash

### ISSUE THREAD

**Issue by pwFoo** [intercoolerjs/intercooler-js#250]
I don't know if it would be much work.
Cash is a minimal jQuery alternative which misses an ajax Plugin and should be jQuery compatible so far...
Dependencies could be even smaller than ZeptoJS.

https://github.com/kenwheeler/cash

**Comment by carsongross** [comment]
Awesome, thank you for the suggestion.  I am going to look at integrating this by default in the intercooler 2.0 release, later this fall, so you won't have to include jquery to use intercooler.

**Comment by pwFoo** [comment]
Any plans about ajax implementation?
Maybe new fetch() api instead of (jQuery) Ajax()?

**Comment by carsongross** [comment]
yep, looking at all the options.  Ideally I'd like to stay jQuery friendly, but work fine without it as well.

**Comment by pwFoo** [comment]
Nice :)
So you'll stay with a framework (like Cash and compatible to jQuery, ZeptoJS) or write VanillaJS?

Base custom framework with selectors, attr(), on(), off(), html(), ... Could bei done with minimal size of some kB's or a custom (reduced) Cash build.

Have you started a 2.0 repo / branch?

**Comment by pwFoo** [comment]
@carsongross 
Another one, even smaller.
https://github.com/edwinm/miq

**Comment by niallobrien** [comment]
Any movement on this? I think most people would be fine going with a lighter alternative and no necessarily requiring jQuery.

**Comment by OvermindDL1** [comment]
If you are curious about the impact of removing jquery from a similar project, it was quite a bit more than *substantial*:
https://blog.makandra.com/2019/01/performance-impact-of-removing-jquery/

**Comment by chg20** [comment]
I get it. I really want to do this, it's just a matter of finding the right time with my business and family.

**Comment by kitepad** [comment]
How about progress for this?

**Comment by chg20** [comment]
Yep, there sure is:

https://kutty.org

jQuery-free intercooler 2.0  :)
