### ISSUE TITLE
Modifiers for ic-action-target are not respected

### ISSUE THREAD

**Issue by vborovikov** [intercoolerjs/intercooler-js#251]
Looking at the code I see I can use `ic-*-action-target` attribute along with the `ic-*-action`. But its value isn't actually used to get the target for an action. Instead, Intercooler tries to use the regular `ic-action-target` or `ic-target` even if the more specific attribute, i.e. `ic-beforeSend-action-target`, is present.

I believe it is a bug in the function [invokeLocalAction](https://github.com/LeadDyno/intercooler-js/blob/91346e36f700f65e03b7e8da45f27acec75dbf9e/src/intercooler.js#L1517). 

I rewrote the beginning of the function and it seems to work as expected:
```javascript
  function invokeLocalAction(elt, actions, modifier) {
    var actionTargetAttr = 'ic' + modifier + '-action-target';
    var actionTargetVal = closestAttrValue(elt, actionTargetAttr);
    if (actionTargetVal === null && modifier !== "") {
      actionTargetAttr = 'ic-action-target';
      actionTargetVal = closestAttrValue(elt, actionTargetAttr);
    }

    var target = null;
    if(actionTargetVal) {
      target = getTargetImpl(elt, actionTargetAttr);
    } else {
      target = getTarget(elt);
    }
  // ...skipped
```

**Comment by carsongross** [comment]
thank you for catching this.  can you create a pull request with this fix (and, ideally, tests?)

**Comment by carsongross** [comment]
Hello, can I ask again for a pull request on this?

**Comment by vborovikov** [comment]
I'm on it.
