### ISSUE TITLE
Avoid XML Parsing errors on redirect header only responses

### ISSUE THREAD

**Issue by Immortalin** [intercoolerjs/intercooler-js#253]
Redirect responses with the IC-x-redirect header works but also raises XML parsing errors if the response body is empty.

**Comment by carsongross** [comment]
Can you create a test case for this?  This may be a response content/internal jquery thing.  We should definitely handle empty response bodies (I use that all the time)

**Comment by Immortalin** [comment]
To clarify, the side effects, i.e. redirect, works fully according to spec. The error messages are logged to console only and does not affect application usability at all.

**Comment by carsongross** [comment]
that's good to hear, at least it isn't a fatal issue

can you clarify the response type for the request?  I don't think this is actually in the intercooler code, I suspect it is in jquery
