### ISSUE TITLE
dependencies.html page disappeared

### ISSUE THREAD

**Issue by jon49** [intercoolerjs/intercooler-js#263]
I know I recently looked at the page http://intercoolerjs.org/dependencies.html and there are links to it everywhere but the actual page is a 404. I don't even see it in the list files in https://github.com/intercoolerjs/intercooler-js/tree/master/www

In the interim the page can be found here: http://webcache.googleusercontent.com/search?q=cache:-oQUalnegncJ:intercoolerjs.org/dependencies.html+&cd=1&hl=en&ct=clnk&gl=us

**Comment by scsmash3r** [comment]
@jon49 You can navigate to v.0.3.2 tag in a "Branch" dropdown and check for needed file:
https://github.com/intercoolerjs/intercooler-js/blob/v0.3.2/www/dependencies.html

**Comment by chg20** [comment]
Thank you @scsmash3r

**Comment by jon49** [comment]
I think part of the problem is that there are links to that page but on website it doesn't appear. It's great that it exists in a tagged version. But it still needs to be merged into master so the page will appear on the website, right?

Thanks for finding it though! It's nice to know it wasn't entirely deleted from the code base!
