### ISSUE TITLE
yOffset is not restored correctly after pressing the "Back" button

### ISSUE THREAD

**Issue by baumann74** [intercoolerjs/intercooler-js#268]
Click on a link with ic-push-url="true" and a high y-offset value. When pressing the "Back" button the previous page is shown at the top. It should instead restore the previous the y-offset.

**Comment by baumann74** [comment]
Pull request with a fix is [here](https://github.com/intercoolerjs/intercooler-js/pull/269).

**Comment by piranha** [comment]
Should be closed, fixed in #269
