### ISSUE TITLE
Requests are "leaking"

### ISSUE THREAD

**Issue by joshinda** [intercoolerjs/intercooler-js#278]
I'm using Intercooler throughout the frontend of my Django web app. It's been great.

But I am getting some pretty alarming behaviour with `ic-trigger-from`. I will explain.

So, I have the following snippet of HTML on my page:

```
{% load contract_filters %}
{% if form_render %}
<form method="post" autocomplete="off" action="javascript:void(0);">
{% csrf_token %}
{% endif %}
<div class="node-row"
     id="node_{{ node.id }}_text"
     {% if form_render %}
     ic-post-to="{% url 'contracts:node-text' node.id %}"
     ic-on-beforeTrigger="return suppressIfWithin(evt, elt)"
     ic-trigger-from="document"
     ic-target="closest form"
     {% else %}
     ic-get-from="{% url 'contracts:node-text' node.id %}"
     ic-target="this"
     {% endif %}
     ic-replace-target="true"
>
  <div class="node-indent">{{ node|node_indent }}</div>
  {% if node.display_number %}
  <div class="node-display-number">{{ node.display_number }}</div>
  {% endif %}
  {% include 'contracts/contract_elements/node/node_text.html' %}
  {% include 'contracts/contract_elements/node/node_action.html' %}
</div>
{% if form_render %}
</form>
{% endif %}
```

Here's what the code successfully does:

1. User clicks within a `div` with class `node-row`. At this point `form_render` is `False`.

2. Intercooler sends a GET request, and replaces the `div` with the HTML response. The response is the same snippet, but this time with `form_render` set to `True`.

3. Now the user is able to edit the text for this `node-row` (the `textarea` is in `node_text.html` but it's not relevant for this issue).

4. The user is finished editing text, and they click elsewhere on the page. This triggers a POST request, which saves the updated text and then sends the same snippet back again, with `form_render` set to `False`. So we have a 'toggle' behaviour between viewing and editing.

NOTE: `ic-on-beforeTrigger` simply cancels the request if the user clicks inside the `div` being edited.

Let me repeat: this all operates as expected. A nice property is that at any time, a maximum of one `node-row` is open for editing.

The problem is with request 'leakage'. After editing has finished and the 'readonly' `div` has been slotted back in, Intercooler does not seem to fully dispose of the editable version.

After editing N nodes (including repeats), every subsequent click ANYWHERE on the page triggers N POST requests back to the server, exactly with the url corresponding to the `ic-post-to` attribute set for the editable version of the snippet.

This should definitely NOT be happening. `document` is explicitly specified as a valid value for `ic-trigger-from` in the Intercooler documentation (and in the code). But that is a side point - the core problem is that Intercooler is triggering requests from elements that should no longer exist. I've checked the DOM multiple times and the values of `ic-trigger-id` in the erroneous POST requests correspond to elements that do NOT currently have an `ic-post-to` attribute.

Any thoughts?

![image](https://user-images.githubusercontent.com/5221085/54685485-d82d8d00-4b0e-11e9-95da-4119018ce1cf.png)

**Comment by chg20** [comment]
Can you produce a test case that replicates it? It sounds like we might be holding on to old elements, or potentially multiple elements are triggering the trigger-from.

**Comment by joshinda** [comment]
Ok - I will try writing a test (and maybe fixing the problem if I can work it out!). One thing - about 1/3 of the tests are failing in branch `development` - is this expected?
