### ISSUE TITLE
Documentation for beforeSend.ic event is wrong

### ISSUE THREAD

**Issue by Deimos** [intercoolerjs/intercooler-js#282]
The description in the docs for the `beforeSend.ic` event says:

> Triggered before sending an intercooler AJAX request to the server. The second argument to the event is the data hash, and can be added or removed from to change the values sent to the server.

However:

* The second argument isn't a data hash
* There is no data hash at all, the `data` argument is a string
* Modifying `data` doesn't change the values sent to the server

Could you please update this event's description to something that accurately describes what it's for and what's possible with it? I just spent a fair amount of time trying to figure out why I couldn't get it to work because the description misled me in multiple ways.

**Comment by chg20** [comment]
Hi Deimos,

Very sorry about that.  I think that changed in an earlier version of intercooler and I didn't get to the docs for it.  Fixing it now.

**Comment by Deimos** [comment]
Thanks - is there any event usable for changing the data before it's sent while it's still in hash form, without having to modify a query string?

**Comment by chg20** [comment]
Is this example useful?

http://intercoolerjs.org/examples/modifying_requests.html

**Comment by Deimos** [comment]
Somewhat, but if I wanted to do something like edit the value of one param out of multiple, I'd have to split and then re-join the query string, right?

**Comment by scsmash3r** [comment]
> Somewhat, but if I wanted to do something like edit the value of one param out of multiple, I'd have to split and then re-join the query string, right?

Right - this is how I was doing it too. But if you came to that point where you need to modify the value of some param in a query string, that means you're doing something not quite right in your code logic. You can always explicitly modify the values of params in your code before sending any requests. BeforeSend trigger comes handy if you want to add something to the already prepared query string.

You can also use [URLSearchParams](https://javascriptplayground.com/url-search-params/)
