### ISSUE TITLE
Can X-IC-Remove take a selector?

### ISSUE THREAD

**Issue by ThisNoName** [intercoolerjs/intercooler-js#283]
The Inline Form Validation example accomplished the task by rebuilding HTML control from server side, not sure if that's an ideal solution.

I'm trying to do something like this https://jsfiddle.net/whoever/a0yje248/25/
```
<div id=result>Validation and Confirmation here</div>

<form method="post">
   <input name="email" ic-post-to="/contact/email" ic-target="#result" />
   <input name="lastname" />
   <input type="submit" ic-post-to="/contact" ic-target="#result" />
</form>
```
Basically targeting the same #result div for both email validation and final confirmation screen.  But with this approach, I need to remove the form after successful submit.  I can do it using X-IC-Script, but it seems more elegant if we can just do something like X-IC-Remove : #result

Thought?  Or maybe it's already available or a better option exists?  Thanks.

**Comment by chg20** [comment]
The way I would approach this would be to fire a custom event from the server, and write that bit of code in your X-IC-Script in the place where you hook up all your event handlers. You can then trigger it with the X-IC-Trigger response header.

I've found this to be the most elegant way to keep all my front end code together and coordinate it with back end events.
Cheers,
Carson

**Comment by ThisNoName** [comment]
I ended up using a small script that flips certain properties based on pattern.  I guess trigger would allow more control.  Still think X-IC-Remove should do more though, just by the name of it.   Thanks for the help and what wonderful framework!
