### ISSUE TITLE
Add new attributes to add ic functionality to existing link

### ISSUE THREAD

**Issue by esb** [intercoolerjs/intercooler-js#290]
The 'ic-get-from', 'ic-post-to', 'ic-put-to', 'ic-patch-to' and 'ic-delete-from' attributes all require a url parameter. This is fine if you're coding up your own HTML, but in some instances you don't have control over the links that get generated by some packages, such as pagination gems.

For example, a pagination gem such as Kaminari or Will Paginate spits out a bunch of pagination links, so if you're using Intercooler to request the pages, you end up having to hack the pagination generators to put in the correct 'ic-get-from' attributes.

I've coded up a fairly neat solution to this problem which adds the following attributes - 'ic-get', 'ic-post', 'ic-put' and 'ic-delete'. They all work in exactly the same way as the corresponding attributes in the current code, except that they take the url from the href attribute in the link, instead of as a parameter. This means that you can just add the attribute 'ic-get="true"' to an existing link and get the same result as if you'd built the link with the 'ic-get-from' attribute.

This makes it very easy to create Intercooler links from generated pagination links, for example, without needing to modify any of the generating code, as long as it allows you to provide custom attributes for the link.

If anyone thinks this is a worthwhile addition, then I can code up some test cases and submit a pull request.

**Comment by chg20** [comment]
Hi There,

Have you seen the "ic-enhance" attribute?  It might cover some of these use cases:

http://intercoolerjs.org/attributes/ic-enhance.html

**Comment by esb** [comment]
Sorry. I missed the significance of that attribute.

Yes, it does exactly what I need for this issue. I just didn't connect the two together.

**Comment by chg20** [comment]
Ah, sorry about that.  I wonder if improving the docs would help.

It is a newer feature and a bit more magic than the usual stuff.  :man_shrugging:

**Comment by esb** [comment]
For me, I didn't connect the purpose of the 'ic-enhance' to anything in particular. The documentation might be improved by adding some reasons why you would want to use this feature. The pagination generators example is a pretty good use case.
