### ISSUE TITLE
Support withCredentials for EventSource

### ISSUE THREAD

**Issue by adamstep** [intercoolerjs/intercooler-js#292]
We want to use Intercooler's SSE support through a [Mercure Hub](https://github.com/dunglas/mercure). In order for this to work, we need to pass `{withCredentials: true}` to the EventSource constructor to properly pass the authentication cookie.

Is there a reason not to make a request with credentials when creating the event source?

**Comment by chg20** [comment]
Hi Adam,

I don't see why we shouldn't send it.  I do have one concern:

https://developer.mozilla.org/en-US/docs/Web/API/EventSource/withCredentials

It looks like IE does not support it.  Are you willing to try it out with a locally modified version of intercooler and see how it behaves on IE?

**Comment by adamstep** [comment]
Sure, I'll give it a try. We're using a locally modified version of Intercooler with this change already, so I'll test it out on IE and let you know how it behaves.

**Comment by adamstep** [comment]
From my testing and research, it looks like the entire `EventSource` API is not yet supported in IE/Edge: https://developer.mozilla.org/en-US/docs/Web/API/EventSource

So supporting any SSE features in IE requires the use of a polyfill like [this one](https://github.com/Yaffle/EventSource). The polyfills essentially rely on long-polling using XHR, and IE does support `withCredentials` on a standard XHR request: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials

**Comment by adamstep** [comment]
After some more testing, there is a reason to support `withCredentials` being true or false.

When `withCredentials` is true for a cross-origin request, the response header `Access-Control-Allow-Origin` cannot use a wildcard `*`. This could break some existing setups.

I propose adding a new attribute `ic-sse-with-credentials` that can be set to `true` or `false`. This attribute would be set on the same element as `ic-sse-src`. Thoughts @chg20 ?

**Comment by chg20** [comment]
Yep that sounds right to me. 

Cheers,
Carson

**Comment by chg20** [comment]
@adamstep any patch for this?

**Comment by adamstep** [comment]
@chg20 yes, I have something that needs to be cleaned up a bit. Will send in the next few days.
