### ISSUE TITLE
ic-include not working

### ISSUE THREAD

**Issue by ericridgeway** [intercoolerjs/intercooler-js#295]
Note my `ic-include` on line 1:
```
    <form ic-get-from="#" ic-include="#player_select">
      Square
      <br>Row: <input name="row">
      <br>Col: <input name="col">

      <input type="hidden" name="place_island" value="square">
      <input type="submit" style="display: none">
    </form>
```

And elsewhere on the page I have the `#player_select` to tell me if I'm Player1 or Player2:
```
  <form id="player_select">
    <input type="radio" name="which_player" value="player1" checked="checked">Player1
    <br><input type="radio" name="which_player" value="player2">Player2
  </form>
```

No matter what variations I try tho, when I submit, I only receive
`Parameters: %{"col" => "asdasd", "place_island" => "square", "row" => "12345"}`

I don't get `"which_player" => "player2"` even though that's what the ic-include is supposed to be for

Help please if able, wonderful beautiful human beings, makers of incredible library! xD <3

**Comment by scsmash3r** [comment]
As far as I can see from your structure, you have form1 and form2.
Why do you have an input, which is needed to be in form1, placed inside form2?

I think you should place your `which_player` radio buttons inside form1:
```
   <form ic-get-from="#" ic-include="#player_select">
      Square
      <br>Row: <input name="row">
      <br>Col: <input name="col">

      <input type="hidden" name="place_island" value="square">
      <input type="submit" style="display: none">

      <input type="radio" name="which_player" value="player1" checked="checked">Player1
      <br><input type="radio" name="which_player" value="player2">Player2
    </form>
```

Is it some acrhitecture requirement that you're placing `which_player` radiobutton separately?

**Comment by ericridgeway** [comment]
Thank you for the reply. I didn't merge the forms because it's not Form 1 and Form 2 unfortunately, it's Form 1, and Form's 2-15. There's a ton of shape forms that only submit themselves and the row/col filled in for them. They just also need to Include `which_player`

And I don't quite understand what you meant by I need the radiobuttons, not the form. There are *multiple* radio buttons, so they can't share an id. I wrapped them in the form and assumed that was how you caught a group of radio's with ic-include, but I surely could have been wrong

What's the correct way then? Do I need to give each radio button input a unique id and make seperate ic-include for each one of them? `ic-include="#radio_player1"`, `ic-include="#radio_player2"`...

That could get painful but I'll do it if that's correct =)

**Comment by ericridgeway** [comment]
Basically I need an example of how ic-include is supposed to work with radio button inputs, if possible. Ty so much for the help <3

**Comment by chg20** [comment]
Hi Eric,

Can you try this:

ic-include="[name='which_player']"

I think you should be able to include the input directly.

I'll add some tests around radio buttons, sorry for the trouble.

**Comment by scsmash3r** [comment]
> Thank you for the reply. I didn't merge the forms because it's not Form 1 and Form 2 unfortunately, it's Form 1, and Form's 2-15. There's a ton of shape forms that only submit themselves and the row/col filled in for them. They just also need to Include `which_player`
> 
> And I don't quite understand what you meant by I need the radiobuttons, not the form. There are _multiple_ radio buttons, so they can't share an id. I wrapped them in the form and assumed that was how you caught a group of radio's with ic-include, but I surely could have been wrong
> 
> What's the correct way then? Do I need to give each radio button input a unique id and make seperate ic-include for each one of them? `ic-include="#radio_player1"`, `ic-include="#radio_player2"`...
> 
> That could get painful but I'll do it if that's correct =)

You can give them some class and `ic-include` the elements like this:

```
<input type="radio" class="radiobutton" name="which_player" value="player1" checked="checked">
<input type="radio" class="radiobutton" name="which_player" value="player2">
...
ic-include=".radiobutton"
// or
ic-include="input[name=which_player]"
```

**Comment by ericridgeway** [comment]
Ty for the help guys. I wasn't able to get any of the 3 variants working
```
ic-include=".radiobutton"
ic-include="input[name=which_player]"
ic-include="[name='which_player']"
```

But I may have just been setting it up wrong. If it works for you then it's my fault and no worries.

Thank you for the help, I love your project so much!
