### ISSUE TITLE
Downloads for minified version not working

### ISSUE THREAD

**Issue by brejoc** [intercoolerjs/intercooler-js#301]
Seems like the downloads for version 1.2.2 and 1.2.3 are not working. I'm getting a 404.

http://cdn.intercoolerjs.org/intercooler-1.2.3.min.js
http://cdn.intercoolerjs.org/intercooler-1.2.2.min.js

**Comment by chg20** [comment]
Fixed.  Sorry about that.

**Comment by brejoc** [comment]
No worries. Thanks!
