### ISSUE TITLE
ic-push-url with custom location

### ISSUE THREAD

**Issue by BartChris** [intercoolerjs/intercooler-js#304]
Hi,

as stated in [https://intercoolerjs.org/attributes/ic-push-url.html](https://intercoolerjs.org/attributes/ic-push-url.html) ic-push-url takes the location of the ajax-request and pushes it into the location bar. 
In some cases the URL of the ajax request does not represent the whole page, but only a specific element on the page. Is there any way to push either a custom URL or the URL of the href-attribute, which represents the complete page, to the location bar?

Best
Chris

**Comment by chg20** [comment]
Hi Bart,

It isn't perfect, but you can use the X-IC-PushURL response header in that case to push a new location.

ic-push-url should probably take either "true" of the actual URL you wish to push as a potential value.  Any interest in taking a crack at that?  :)

**Comment by BartChris** [comment]
Hi Carson,
i will take a look, if i find the time and if this does not exceed my capacity. It would be a very useful feature, so i would be happy if somebody implements this. Thanks for Intercooler btw. ;)

**Comment by chg20** [comment]
No prob.  I'll close out the issue.
