### ISSUE TITLE
It appears the google group is gone

### ISSUE THREAD

**Issue by undernewmanagement** [intercoolerjs/intercooler-js#307]
When I attempt to access the group I get the following message:

<img width="551" alt="image" src="https://user-images.githubusercontent.com/351998/71836390-2b7bc680-30b4-11ea-9bf8-7771b06f5015.png">

Has the group been deleted or is this simply a permission thing?

I would be interested to help setup a proper forum like discourse because I believe in the cause :-)

**Comment by jsampson** [comment]
I can get to the group but it does say "shared privately". If I access it in an incognito window I see the same error as above.

https://groups.google.com/forum/#!forum/intercooler-js

@chg20 anything change recently?

**Comment by chg20** [comment]
Hmm, there is a message saying that permissions have recently changed.  I tried updating view permissions, can you try again?

**Comment by jsampson** [comment]
Yep, appears to be fixed. It says "shared publicly" and I can access it incognito now.

**Comment by adamstep** [comment]
Confirmed working for me as well now.
