### ISSUE TITLE
Default  values not displayed on refresh

### ISSUE THREAD

**Issue by Arico1985** [intercoolerjs/intercooler-js#308]
hello hello - new one: under what circumstances, using IC, would refreshing a browser not update variable values to their default value ?

I have a form injecting month & year in a calendar using IC. Everything works perfectly but when i refresh the web browser, the default values for the form are not displayed on the web page.

Relevant parts of the template:
```
<div id="page-content">

  <div class="container">
        <form ic-post-to="{% url 'home' %}"
        method="post"
        ic-target="#page-content"
        ic-select-from-response="#page-content">
                    {{form.month}}
                    {{form.year}}
       <button type="submit" class="btn btn-success text-right" value="Save">{% trans "Go" %}</button>
        </form>
  </div>
  
  <div> [ code for the calendar ] </div>
  
 </div>
```

Relevant part of the view:
```
def home(request, year=date.today().year, month=date.today().month):

    if request.method == 'POST':
        form = MyDateForm(request.POST)
        if form.is_valid():
            year = int(form.cleaned_data['year'])
            month = int(form.cleaned_data['month'])
    else:
        form = MyDateForm()

    context = {
        'month': _(calendar.month_name[month]).capitalize(),
        'year': year,
        'form': form,
    }
```

and in the form I have:
```
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.initial['month'] = datetime.date.today().month
        self.initial['year'] = datetime.date.today().year
```

**Comment by adamstep** [comment]
Can you explain the overall experience you're trying to implement? If I understand correctly, you have an input widget for selecting a month and year, and then you want to update a calendar view below the input widget when the date is changed. Is that right?

**Comment by Arico1985** [comment]
That's correct. And the code above works. The issue I have is that , on refresh, the default value for the form is not displayed. 

In more detail:
1) the user select , say, `March` and `2020`
2) press `submit`
--> the calendar is correctly updated
3) then say the user presses refresh
--> the calendar gets correctly updated with the default values (today's month and today's year)
But the form still shows `March` and `2020`.

What is interesting as well is that the page source shows that the form is correctly updated with today's month and today's year but the page still displays `March` and `2020`.

Does this make sense ?

**Comment by adamstep** [comment]
Yes, that makes sense but I don't think it's related to Intercooler. Check out this gist where I think I captured a UI similar to what you explained: https://gist.github.com/adamstep/186c56500afd05b4179e562b9cbe5b42

When I refresh, I get the same default date in the input and the display below. It sounds like maybe the web browser is remembering the previous input. Which browser are you using to test?

**Comment by Arico1985** [comment]
I see, thank you for testing. I am using Firefox. Anyway you think I could prevent that from happening ?

**Comment by Arico1985** [comment]
turns out it's a Firefox-specific issue. This helped: https://stackoverflow.com/questions/4831848/firefox-ignores-option-selected-selected


I added an id to my form and :
```
window.onload = function() { document.forms['date_form'].reset(); };
```
to my js and all is well.

Thank you for your help Adam !
