### ISSUE TITLE
How get and populate different targets with a single POST request

### ISSUE THREAD

**Issue by matdrapeau** [intercoolerjs/intercooler-js#312]
I have a `form` which is divided in different tabs (wizard-like style).
When an input field is changed, every tab sub-contents should be modified (defined by a distinct div id).
I currently have each tab to be triggered by a form change and doing its own update individually.

It appears to be sub-optimal since I could only do a single request, get the full form and update by `ic-target` and `ic-select-from-response`. I am not sure how to organize ic tags in order to have a list of targets but a single `ic-post-to`.

**Comment by chg20** [comment]
If you want to make it one request, the only real option is to expand the target element to include all the elements you want updated unfortunately.  

You could use the dependency mechanism if you want to avoid triggering a bunch of events, but I have come to prefer explicit events to the implicit dependency stuff.

**Comment by matdrapeau** [comment]
@chg20 thanks for your response!
Yes the response is containing all elements. So, how to update all targets based on different selectors within this single response?

**Comment by chg20** [comment]
Hello,

I never came up with a good solution for this for intercooler 1.0, but I am beginning work on intercooler 2.0, renamed kutty, and it will support out of band swaps in responses:

https://kutty.org/docs#oob_swaps
