### ISSUE TITLE
Can ic-get-from include value of triggered input?

### ISSUE THREAD

**Issue by BoPeng** [intercoolerjs/intercooler-js#313]
I am trying to do AJAX query from user input using 

```
      <input type="text" 
        id="search-member"
        placeholder="Typing to search users to add"
        ic-trigger-on="keyup changed"
        ic-trigger-delay="500ms"
        ic-target="#member-table"
        ic-get-from="/search"
      >
```
but the query does not include the current value in `input`. Is there way to do it or do I have to use a `<form>` with `ic-post-to`?

**Comment by chg20** [comment]
Can you put a name on the input as well?  It should be included in that case.

**Comment by BoPeng** [comment]
Cool! I get the value through the name of `input`...

I did search the documentation and could not find this information. Please add it if I have not missed something obvious. I suppose an extra sentese such as "The value of the input is passed as value of the name of the input with the request" in `https://intercoolerjs.org/examples/activesearch.html` would suffice.
