### ISSUE TITLE
Prepend element before a target and remove element afterwards

### ISSUE THREAD

**Issue by BoPeng** [intercoolerjs/intercooler-js#314]
Thanks to `intercooler.js` I have implemented a hugely complex (to me) group membership management interface without a single line of JS. Right now I am at the last step to add member in the following a layout

```
Box - group title
row - member_1
row - member_2
row - [input -> AJAX]
row - potential-member_1     [add button]
row - potential-member_2     [add button]
```
Here the potential-members are populated and appended by entering text in the `AJAX input`.

By clicking `add button`, two things are supposed to happen

1. A `row - new member` would **prepend before** `[input -> AJAX]` row. This does not seems to be possible because `ic-swap-style="prepend"` to the `input` `row` will insert the item inside and create `<row> row - new member [input ] </row>`. It looks like I am in need of something in parallel to `ic-replace-target`, namely `ic-prepend-target`.

2. After the item is inserted I will need to remove the `potential-member` row to avoid repeated insertion. I cannot yet figure out how to perform two frontend actions.

My best approach now is to replace the entire `Box`, but the whole box will redraw and the search box will be cleared so users cannot add multiple members with one search.

**Comment by BoPeng** [comment]
I think for the first problem I can do

```
Box - group title
row - member_1
row - member_2
[empty div placeholder]
row - [input -> AJAX]
row - potential-member_1     [add button]
row - potential-member_2     [add button]
```
and replace 
```
[empty div placeholder]
```
with
```
row - new member
[empty div placeholder]
```

**Comment by chg20** [comment]
Hi There,

I can think of a few approaches:

1) Group the top stuff

Box - group title
row - member_1
row - member_2

into a div and then use an ic-append targeting that div, and then something like ic-action and ic-action-target to remove the row that is clicked on:

http://intercoolerjs.org/attributes/ic-action.html

A less complicated set up would be to target the entire bit of HTML, but preserve the input value when you render it.  The input would lose focus but they user has already clicked out of it to select a contact, so that shouldn't be too bad.

**Comment by BoPeng** [comment]
Yes I agree that there are several solutions. I thought of your idea but in my case the members are `row`s that are immediate children of `Box`, having `Box -> Div -> Row` will mess up some of the `css` so I choose to have a placeholder and replace it with a `Row + placeholder`. However, even without an intermediate `div`, your solution would work if I move the `input` element out of `Box` because it does not belong there anyway.

That said, I cannot see why [ic-swap-style](http://intercoolerjs.org/attributes/ic-swap-style.html) is limited to 

> The value of the attribute should be one of 'replace', 'append', 'prepend'

I mean, instead of having

```
ic-target + ic-swap-stype (three ways to change content of `ic-target`)
ic-target + ic-replace-target (one way of replacing `ic-target`)
```

I think it is natural to allow `ic-swap-style` to have

```
 'replace-target', 'append-target', 'prepend-target'
```

in addition to 
```
 'replace', 'append', 'prepend', and
```
with the `-target` version being replacing the target entirely, appending new html after target, prepending new html before target.

For the second question i did not know that `ic-action` could be specified with `ic-post-to` because I had the feeling that only one "action: could be specified at a time.

**Comment by chg20** [comment]
Hello,

Update on this issue: I have begun working on intercooler 2.0, renamed kutty

https://kutty.org

And it specifically supports different swap types as you have outlined.  I hope to release a 0.0.1 this friday.

**Comment by BoPeng** [comment]
Great. Congratulations on the new version/project and I look forward to using it. I think the biggest missing piece for intercooler.js is multi-element (maybe 2 is enough) actions such as "switch a tab and activate ...", "remove a row and enable".... although I do not know if and how kutty can enable these.
