### ISSUE TITLE
Progressive Enhancement Functionality

### ISSUE THREAD

**Issue by chg20** [intercoolerjs/intercooler-js#78]
I’d like to look at a mode/attribute for intercooler that uses Progressive Enhancement:

  https://en.wikipedia.org/wiki/Progressive_enhancement

where you can transform all your links and forms into intercooler-based AJAX requests using the normal attributes, but they keep working “the normal way” if you don’t have javascript enabled.

**Comment by n3storm** [comment]
great!

**Comment by mahony0** [comment]
looking this enhancement for me too disabling js sometimes for some reasons, like as plenty amount of other web users..
